# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: sangwoohan
google_analytics: guyya
title: Make Exclusive

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Make Exclusive

description: Blog for game development history...
author:
  name: guyya
  email: guyya@ismaildemirbilek.com
  github: guyya
  twitter: guyya
  pinterest: guyya
  linkedin: guyya
  bio: Game Server Programmer
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
